### ISSUE TITLE
Add return after sending response

### ISSUE THREAD

**Issue by nikoleta-vukajlovic** [argoapp-live/argo-api#185]
https://github.com/argoapp-live/argo-api/blob/9b7d848c4e9272b597e15581d2270f08fdded0d2/src/components/Subscription/index.ts#L95

**Comment by rekpero** [comment]
Is this Fixed? @nikoleta-vukajlovic

**Comment by nikoleta-vukajlovic** [comment]
No, should we create new branch for those 3 issues for bugs that we found when writing tests?
