### ISSUE TITLE
Pagination details

### ISSUE THREAD

**Issue by rekpero** [argoapp-live/argo-api#188]
- [x] Get the total number of maintained & archived projects
- [x] Get the total number of organization payments
- [x] Get deployment count details like total deployment, failed deployment, pending deployment, successful deployments

**Comment by nikoleta-vukajlovic** [comment]
Do you want deployment count details for project or for organization?

**Comment by rekpero** [comment]
> Do you want deployment count details for project or for organization?

For the project only
