### ISSUE TITLE
Got a bug in get roles call

### ISSUE THREAD

**Issue by rekpero** [argoapp-live/argo-api#191]
Might be a migration issue but check the error and let me know if this is a migration issue or something else.

When I made a call to this endpoint: 
```
http://localhost:8080/role/getUsersWithRoleGroups/5f7e264c393ba800476a12b2
```
I'm getting this error from API:
```
Error: Cannot read property 'id' of null
    at /Users/mitrasish-personal/Documents/Workspace/ArGo/argo-api/src/components/Role/index.ts:343:10
```

**Comment by nikoleta-vukajlovic** [comment]
One user in users array of organization did not exist so we removed him.  Also singleApple user was created on old code so he did not receive role attached to him.

**Comment by nikoleta-vukajlovic** [comment]
Yes, we removed users that were not valid. Should work now

**Comment by rekpero** [comment]
> Yes, we removed users that were not valid. Should work now

ok cool
