### ISSUE TITLE
New Deployment creation is not mapping to correct organization

### ISSUE THREAD

**Issue by rekpero** [argoapp-live/argo-api#23]
## Acceptance Criteria: 
- the project should be mapped to the selected org during deployment.
- UI is sending the correct organization id when deploying but it's not mapped to the correct organization.

### New deployment on Orca org

![image](https://user-images.githubusercontent.com/34746546/94349909-c8c5c300-0066-11eb-83cc-2bb113cfdd5b.png)

### Id is the same as the Orca org

![image](https://user-images.githubusercontent.com/34746546/94349927-e3983780-0066-11eb-9888-e9bcfe5ede2e.png)

### Not getting all the repo

![image](https://user-images.githubusercontent.com/34746546/94349948-0c203180-0067-11eb-9e41-9d81e16ab9b3.png)

**Comment by izrake** [comment]
@rekpero I have checked in the fix. Also tested it is working as expected please retest and close the bug

**Comment by izrake** [comment]
closing bug. Tested and demoed
