### ISSUE TITLE
Provide api end point to support user profile view and to edit

### ISSUE THREAD

**Issue by rekpero** [argoapp-live/argo-api#3]
There is a requirement of 3 endpoints:

- `GET /api/profile` - fetch all the user details from DB.
- `PUT /api/profile/:id` - update with new user details. The update is only on Argo specific user details, not GitHub/GitLab.
- `POST /api/profile/:id` - deactivate the user

**Comment by izrake** [comment]
closing this issue. Integrated and tested with UI
