### ISSUE TITLE
User should be able to invite user using user email id

### ISSUE THREAD

**Issue by izrake** [argoapp-live/argo-api#9]
## Issue

1. Creation of user invite mail template
2. Allowing only invited user inside the organization

_Note: This will also involve Mongo DB schema creation_

## Acceptance
1. User should be able to send an invite
2. Once user logins using referral mail then the user should able to see the invited organization and should be able to perform normal user actions on the ARGO UI

**Comment by rekpero** [comment]
Integrated with UI and tested E2E.
